---
# tasks file for clickhouse-role
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  ignore_errors: true

- name: Install prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
    state: present
  ignore_errors: true

- name: Add ClickHouse repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main"
    state: present
    filename: "clickhouse.list"
  ignore_errors: true

- name: Install ClickHouse packages
  become: true
  ansible.builtin.apt:
    name:
      - clickhouse-server
      - clickhouse-client
    state: present
  notify: Start clickhouse service

- name: Create database
  ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0


