---
# tasks file for lighthouse-role
- name: Allow release info change for apt
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/99releaseinfochange
    state: present
    create: true
    line: 'Acquire::AllowReleaseInfoChange::Suite "true";'
    mode: "0644"
  when: ansible_pkg_mgr == "apt"

- name: Install Nginx and dependencies
  ansible.builtin.apt:
    name:
      - nginx
      - unzip
      - git  # Добавляем git для совместимости с подходом рабочей роли
    state: present
    update_cache: true

- name: Download Lighthouse static
  ansible.builtin.get_url:
    url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/gh-pages.zip"
    dest: "/tmp/lighthouse.zip"
    mode: "0755"

- name: Create web directory
  ansible.builtin.file:
    path: /var/www/lighthouse
    state: directory
    mode: "0755"

- name: Unarchive Lighthouse
  ansible.builtin.unarchive:
    src: "/tmp/lighthouse.zip"
    dest: "/var/www/lighthouse"
    remote_src: true
    extra_opts: ["--strip-components=1"]
  notify: Restart Nginx

- name: Configure Nginx
  ansible.builtin.template:
    src: "templates/nginx-lh.conf.j2"
    dest: "/etc/nginx/sites-available/lighthouse.conf"
    mode: "0644"
  notify: Restart Nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/lighthouse.conf"
    dest: "/etc/nginx/sites-enabled/lighthouse.conf"
    state: link
  notify: Restart Nginx

- name: Disable default site
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Restart Nginx
