version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.3.3.44
    container_name: clickhouse-01
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
     test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
     interval: 10s
     timeout: 30s
     retries: 15
     start_period: 60s
  vector:
    image: timberio/vector:0.34.0-alpine
    container_name: vector-01
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./vector.yml:/etc/vector/vector.yml
    command: ["--config", "/etc/vector/vector.yml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8686/health || exit 1"]
      interval: 10s
      timeout: 2s
      start_period: 10s