galaxy_info:
  role_name: lighthouse
  author: Sergei Kuskunakov
  namespace: sergeikoost
  company: sergeikoost
  description: Role for installation Lighthouse

  license: MIT

  min_ansible_version: "2.11"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
